# Generated by Django 3.1.7 on 2021-04-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='repair_request',
            name='phone',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='repair_request_photo',
            name='phone',
            field=models.CharField(max_length=18),
        ),
    ]
