# Generated by Django 3.1.7 on 2021-04-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210420_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo1', models.ImageField(upload_to='')),
                ('photo2', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('evaluation', models.CharField(choices=[('1', 'Плохо'), ('2', 'Неплохо'), ('3', 'Нормально'), ('4', 'Хорошо'), ('5', 'Отлично')], default='5', max_length=1)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='services',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
