# Generated by Django 3.1.7 on 2022-12-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20221207_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo1',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo2',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='repair_request_photo',
            name='img1',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
